### ISSUE TITLE
How do we want to classify the segments?

### ISSUE THREAD

**Issue by Irene-Xu-mengye** [jwu13/Mini-Kuakua3#1]

**Comment by jwu13** [comment]
Here is an interesting way of classification I came up with:

# Varsity Trail (The hardest trail: Long total length + high variation in elevation changes)
Snowmobile Trail

The trail is both long in distance and changes frequently in elevation. It is both time-consuming and exhausting to hike. Energetic people who are in good health condition, such as varsity team members, are most suitable for this trail. 

## Camping Trails (Long total length + medium variation in elevation changes)
Western Loop
Eastern Loop
Poplar Hill Road

These trails are long in distances and but elevations of the trails do not change quickly. These trails take a long time to hike but are not energy-consuming as elevations change slowly. Also, hikers are able to enjoy various sceneries along the road as trails are long in distances. People who want to have fun in MacLeish but do not want an exhausting trip, such as camping beginners, are most suitable for these trails. 

### Sweat Trail (Medium total length + high variation in elevation changes)
Porcupine Trail

Thes trail is medium in terms of length and but its elevation changes quickly. Finishing this trail will not be time-consuming. However, it may be exhausting to hike as the elevation changes quickly. People who want a quick work-out are most suitable to hike this trail.

#### Grandma Trails (The easiest trails: short total length + low variation in elevation changes)
Vernal Pool Loop
entry trail
Easy Out 
Driveway

These trails are both short in distances and elevation of the trails change slowly. These trails are relaxing to hike. People who are in relatively weak health conditions are most suitable to hike this trail.
